### ISSUE TITLE
npm install, type string undefined

### ISSUE THREAD

**Issue by alvarotroya** [MikeDabrowski/franz#8]
Hi, 

I am trying to install your fork on Franz on my laptop. I cloned the repository, cd'ed into it and ran npm install.
I obtained the following error:

>lerna ERR! npm run prepare stdout:
\>@meetfranz/forms@1.0.9 prepare /home/alvaro-uni/repos/franz/packages/forms
\>tsc
>src/button/index.tsx(237,11): error TS2322: Type 'string | undefined' is not assignable to type '"button" | "reset" | "submit" | undefined'.
  Type 'string' is not assignable to type '"button" | "reset" | "submit" | undefined'.

I am on Ubuntu Gnome 16.04, node v11.5.

Any help is very appreciated!
![Screenshot from 2019-05-15 13-41-23](https://user-images.githubusercontent.com/29738568/57773209-c7b51f80-7717-11e9-916d-277e79a0f906.png)

**Comment by MikeDabrowski** [comment]
Interesting problem. I haven't touched the code since march. 
I just tried npm i on my windows machine and got huge list of errors. However, yarn just did its job and installed everything correctly. Maybe try with yarn.

You can try to use some workaround with `any` on that type or maybe some type assertion ` ... as "button" | ...`.

I will try to update code from original fork, but I'm very busy right now, so can't promise anything.

**Comment by alvarotroya** [comment]
Thanks for checking the issue. Unfortunately yarn didn't help in my case. It runs 
`npm run prepare` at some point and the same error ocurrs.

![Screenshot from 2019-05-15 20-16-18](https://user-images.githubusercontent.com/29738568/57799062-7bd19d00-774e-11e9-8310-0b6ac372c03c.png)

Thank you for fixing the issue whenever you have time for it!
